spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: user_svc
    password: user_pass
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: msuser_admin
    password: msuser_mdp

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/